# -*- coding: utf-8 -*-
"""AlproWeek7-2(6).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Af4EcZmNbzttpRWbSmnutwzuOHmVOlRZ
"""

n = int(input('Jumlah angka yang akan dimasukkan: '))
e = []
freq = {}
e_dup = []

for i in range(n):
  num = int(input(f'Masukkan angka {i+1}: '))
  e.append(num)

for num in e:
  if num in freq:
    freq[num] += 1
  else:
    freq[num] = 1

for num, count in freq.items():
  if count > 1:
    e_dup.append(num)

print(e_dup)

