# -*- coding: utf-8 -*-
"""Alpto Week7 -2(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFRJhW_K1_PIuy8QHdRIcEAT1zdfqewK
"""

input_str = input('Masukkan kata-kata: ')
stack_rev = ''

stack = input_str.split()[::1]

while len(stack) != 0:
    stack_rev += stack.pop() + ' '

print(stack_rev)

