# -*- coding: utf-8 -*-
"""Alpto Week7 -2(2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZ78k3z6f7-2SW44p3Wp45NGse1sk1yS
"""

n = int(input('Jumlah yang ingin dimasukkan: '))
num_input = []
stack = []
reverse_input = []

for i in range(n):
  num = int(input(f'Angka {i+1}: '))
  num_input.append(num)

for i in num_input:
  stack.append(i)

for i in range(0, len(stack)):
  for j in range(i+1, len(stack)):
    if stack[i] <= stack[j]:
      stack[i], stack[j] = stack[j], stack[i]

while len(stack) > 0:
  reverse_input.append(stack.pop())

print(reverse_input)

