# -*- coding: utf-8 -*-
"""AlproWeek7-2(7).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xBeUJsu1SvwZjwpcQRMn_WAjGO6mIoW
"""

n = int(input('Junlah angka yang akan di masukkan: '))
k = int(input('Angka kelipatan: '))
e = []
e_out = []

for i in range(n):
  num = int(input(f'Masukkan angka {i+1}: '))
  e.append(num)

for i, v in enumerate(e):
  if v % k != 0:
    e_out.append(v)

print(f'Output: {e_out}')

