# -*- coding: utf-8 -*-
"""Alpto Week7 -2(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBXAE5Xuxd8Z6zMVk2KA6QDVLa_WtDV7
"""

#mengambil input dari user
input_str = input('Input: ')
#array kosong untuk membuat stack
stack = []
#variable untuk menyimpan input yang sudah di lakukan reverse
reverse_str = ''

#looping setiap karakter yang ada di input_str lalu masukkan dalam stack
for i in input_str:
  stack.append(i)

#looping saat jumlah value dalam stack lebih besar dari pada 0
while len(stack) > 0:
  #isi dari reverse_str akan di tambahkan dari stack (dari urutan belakang) lalu di hapus
  reverse_str += stack.pop()

print(f'Output: {reverse_str}')

