# -*- coding: utf-8 -*-
"""Alpto Week7 -2(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13h3K8w2HHBa_bZvXhZNTOiFUhVJdb9rn
"""

n = int(input('Jumlah input yang ingin dimasukkan: '))
num = []

for i in range(n):
  input_num = int(input(f'Angka {i+1}: '))
  num.append(input_num)

for j in range(0,len(num)):
  for k in range(j+1, len(num)):
    if num[j] >= num[k]:
      num[j], num[k] = num[k], num[j]

while len(num) != 1:
  num.pop(-1)

print(f'Output: {num}')

